package net.microscraper.util;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import net.microscraper.database.Scope;

/**
 * A class to keep track of scope generation during tests.
 * @author realest
 *
 */
public class ScopeGenerator implements Iterator<Scope> {
	private final List<Scope> scopes = new ArrayList<Scope>();
	private final UUIDFactory factory = new IntUUIDFactory();
	
	/**
	 * Always <code>true</code>.
	 */
	public boolean hasNext() { return true; }
	
	/**
	 * Increment the {@link ScopeGenerator} and return the next scope.
	 */
	public Scope next() {
		scopes.add(new Scope(factory.get()));
		return scopes.get(scopes.size() - 1);
	}
	
	/**
	 * Decrement the {@link ScopeGenerator}.
	 */
	public void remove() {
		scopes.remove(scopes.size() - 1);
	}
	
	/**
	 * 
	 * @return How many times the {@link ScopeGenerator} has been incremented.
	 */
	public int count() {
		return scopes.size();
	}

	/**
	 * 
	 * @return The first value in the {@link ScopeGenerator}.
	 */
	public Scope first() {
		return scopes.get(0);
	}
	
	/**
	 * 
	 * @return A {@link List} of all the {@link Scope}s generated by this {@link ScopeGenerator}.
	 */
	public List<Scope> all() {
		return scopes;
	}
	
	/**
	 * 
	 * @return The last value in the {@link ScopeGenerator}.
	 */
	/*public int last() {
		return start + cnt;
	}*/
}